[package]
name = "simple_rust_chess"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.18"
